apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: spring
spec:
  source:
    git:
      uri: https://github.com/srinath-17/spring-boot-mongo-docker
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: openjdk:8-alpine
      env:
        - name: MAVEN_MIRROR_URL
          value: http://my-maven-mirror.com/repository
  output:
    to:
      kind: ImageStreamTag
      name: spring:latest
